# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ALADI Institucional
    url: http://www.aladi.org/sitioaladi/
  - name: SICOEX
    url: http://consultawebv2.aladi.org/sicoexV2/jsf/home.seam
  - name: Acceso a Mercados
    url: https://www.aladi.org/accesoamercados/
  - name: SCOD
    url: https://www.codaladi.org/aladi/paginasPrivadas/paginaInicioCliente.xhtml

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: /ALADI_Sites_Monitor
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime ALADI
  introTitle: "**Upptime** es un monitor open-source y página de Estado de Sitios, powered by GitHub."
  introMessage: Esta es una página en tiempo real de los sitios de ALADI
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
