# Change these first
owner: Scaldy # Your GitHub organization or username, where this repository lives
repo: ALADI_Sites_Monitor # The name of this repository

sites:
  - name: Web Institucional
    url: $URL_INSTITUCIONAL
  - name: SICOEX
    url: $URL_SICOEX
  - name: Acceso a Mercados
    url: $URL_AAM
  - name: SCOD
    url: $URL_SCOD
  - name: PLGN
    url: $URL_PLGN
  - name: Prueba_No_Existe
    url: https://www.no.existe.google.com
  - name: Prueba_Error_500
    url: $URL_ERROR_500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /ALADI_Sites_Monitor
  baseUrl: /ALADI_Sites_Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Sites
  introTitle: "**Upptime** es un monitor open-source y página de Status, powered by GitHub."
  introMessage: Esta es una página en tiempo real de los sitios web
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
